# Generated by Django 3.2.18 on 2023-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=122, null=True)),
                ('societyName', models.CharField(max_length=122)),
                ('memberName', models.CharField(max_length=122, unique=True)),
                ('flatno', models.CharField(max_length=122)),
                ('openingBalance', models.IntegerField()),
                ('closingBalance', models.IntegerField()),
                ('elcty', models.CharField(blank=True, max_length=122, null=True)),
                ('wtrbll', models.CharField(blank=True, max_length=122, null=True)),
                ('prkng', models.CharField(blank=True, max_length=122, null=True)),
                ('mncpl', models.CharField(blank=True, max_length=122, null=True)),
                ('snkng', models.CharField(blank=True, max_length=122, null=True)),
                ('nccpncy', models.CharField(blank=True, max_length=122, null=True)),
                ('pnlty', models.CharField(blank=True, max_length=122, null=True)),
                ('date_add_member', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SocietyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societyName', models.CharField(max_length=122, unique=True)),
                ('regno', models.CharField(max_length=122)),
                ('address', models.TextField()),
                ('date_add_society', models.DateField()),
                ('user', models.CharField(blank=True, max_length=122, null=True)),
                ('charges_fields', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
