# Generated by Django 3.2.18 on 2023-07-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='societylist',
            name='status',
            field=models.CharField(default='Active', max_length=122),
        ),
    ]
